### ISSUE TITLE
Favicon improviment 

### ISSUE THREAD

**Issue by Mike-Reddick** [jingyu9575/multithreaded-download-manager#101]
make favicon color follow the setting Interface-Icon-White

**Comment by wvxwxvw** [comment]
Changing the icon color does not work for the context menu. In any case it is not necessary to impose on the user the color of the icons. There just has to be a working choice.

**Comment by jingyu9575** [comment]
@Mike-Reddick On my system, the favicon (icon on the tab) can adapt to the theme if `svg.context-properties.content.enabled` is enabled in about:config. Please enable this preference and see what happens.

![image](https://user-images.githubusercontent.com/8923139/71217989-19321800-22c0-11ea-8a48-7aa13da12142.png)

---

@wvxwxvw 

The options works for the context menu of the toolbar button. It does not work for the context menu of the link. This is because Firefox [forces](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/menus/create#Parameters) the icon to be the extension main icon. The extension can only have one main icon, so I use the black one.

Mozilla [refuse to support](https://bugzilla.mozilla.org/show_bug.cgi?id=1488524) automaticaly changing the context menu icon color. Therefore, the icon is still black even if `svg.context-properties.content.enabled` is enabled.

If you use [userChrome.css](https://www.userchrome.org/), you can use the following code to change the context menu icon color to white:

```css
#multithreaded-download-manager_qw_linux-2g64_local-menuitem-_link-context-menu {
	-moz-context-properties: fill;
	fill: white;
}
```

**Comment by Mike-Reddick** [comment]
perfect, thanks for the tip,

**Comment by Mike-Reddick** [comment]
I reopen the issue, because this setting work only to change black to white, but if I use for instance Third Party Icons = 2, the extension favicon do not follow the setting.

**Comment by Mike-Reddick** [comment]
I reopen the issue, because this setting work only to change black to white, but if I use for instance Third Party Icons = 2, the extension favicon do not follow the setting.

**Comment by jingyu9575** [comment]
I've added code to change the favicon if a third-party icon is used. Unfortunately Firefox is very slow to accept new icons. I don't know any workaround.
