### ISSUE TITLE
auto remove illegal characters

### ISSUE THREAD

**Issue by Mike-Reddick** [jingyu9575/multithreaded-download-manager#112]
some times I cant download because of illegal characters, please add setting to auto remove illegal characters

**Comment by Nokia808** [comment]
Yes, I agree. For example look for the following pages:

https://archive.org/details/lp_swan-lake-the-complete-ballet_pyotr-ilyich-tchaikovsky-richard-bonynge-n/

Only the 1st track [introduction (Moderato Assai) 5:55] can be downloaded. To download it you should do the following:
- run the track 
- open "create a download task"  of add-on | select "Media" | enter MP3 in search | select result of search | Download
It will downloaded okay.
But retry with other tracks, all will failed due to illegal characters !

Other link:
https://archive.org/details/lp_sounds-of-three-quarters-of-a-century_minnesota-orchestra-prokofiev-stravinsky/disc1/01.01.+Love+for+Three+Oranges+Suite%2C+Op.+33a.mp3
Using the same way, only 1st 3 tracks can be downloaded while remaining will fail due to illegal characters !
------------
By the way, your add-on do not grasp audio automatically from Internet archive & this is other issue that I will open a special request about it.

**Comment by jingyu9575** [comment]
The invalid characters will be replaced in the next version. `:` will become `-`.

**Comment by Nokia808** [comment]
Many thanks !

**Comment by Mike-Reddick** [comment]
thanks

**Comment by Nokia808** [comment]
@jingyu9575 
Hi. I tested new version & still give me same errors ! It is still not fixed ! Please re-test it on the 2 links that I gave you.

**Comment by jingyu9575** [comment]
@Nokia808 works here. Are you using Windows?

![图片](https://user-images.githubusercontent.com/8923139/72604174-acd82200-391a-11ea-8f3a-7c5927ec96bc.png)

**Comment by Nokia808** [comment]
@jingyu9575 
No, I'm using Fedora Linux 30 X64 bit Cinnamon edition.
I enabled the following options in "Advanced" - see the following screenshot:
![Screenshot](https://user-images.githubusercontent.com/25375330/72606712-ffafda80-3916-11ea-9047-00546db740db.png)

**Comment by jingyu9575** [comment]
@Nokia808 As far as I know, Linux has no restrictions on filename except `/` for path separator and null characters, so I did not enable the fix on Linux. I'll test it.

**Comment by jingyu9575** [comment]
This is on openSUSE 15.1:

![Screenshot_20200117_120617](https://user-images.githubusercontent.com/8923139/72607967-f24c1d80-3921-11ea-82e8-c04061b186ff.png)

The `:` symbol is allowed by Linux, and the extension won't remove it.

Is your download directory in a NTFS partition? That would impose Windows' restrictions.

**Comment by Nokia808** [comment]
@jingyu9575 
1) my drive is Ext4 (version 1.0)
2) these files can not downloaded by buit-in download (only streaming). Only can by downloaded by download manager, like your extension & here exactly your add-on credit !
3) I tried to rename one of my .docx file. I renamed it into ? & it worked & opened by LibreOffice. Then I renamed it to : & it worked & opened by LibreOffice okay !

**Comment by jingyu9575** [comment]
@Nokia808 I've looked into Firefox source code. Apparently they got some [issues](https://bugzilla.mozilla.org/show_bug.cgi?id=1562176) with saving the *about:memory* page, but instead of fixing the links, they just disallowed download filenames with `:` even on Linux. The openSUSE computer I used has Firefox ESR 68 that has not been updated with this restriction.

The next version of the extension will replace `:` on all systems.

**Comment by Nokia808** [comment]
@jingyu9575 
It is working now ! Many thanks !

**Comment by mo-han** [comment]
Please re-open this issue, similar bug here, but I've no idea which char is illegal at all. The download source has a rectified filename which illegal chars are already removed - yes, the site did that automatically for the visitors.
![图片](https://user-images.githubusercontent.com/9916948/82973563-5be3e300-a00a-11ea-8b2f-ac1084ea411c.png)

**Comment by jingyu9575** [comment]
@mo-han 

Looks like Firefox does not allow consecutive spaces in the filename, for whatever reasons. The latest version will remove them.

**Comment by mo-han** [comment]
@jingyu9575 
Wow, thank you for this quick fix, really glad to know it was not some tough bug.
BTW, how could you find out that "cosecutive spaces" cause? I didn't see any of them at all...
