### ISSUE TITLE
No automatic grab audio & archive files from Internet Archive !

### ISSUE THREAD

**Issue by Nokia808** [jingyu9575/multithreaded-download-manager#114]
Hi. I noticed that your add-on do not grab audio files, like .mp3, nor archive files from Internet Archive though it support multithreaded download !

This issue is similar to problem of automatic grab of PDF that you are already fix it - see https://github.com/jingyu9575/multithreaded-download-manager/issues/88
You can add similar option for such audio, as you already did for PDF files.
Regarding archive files, I think your add-on should always grasp them ....

Example pages:
https://archive.org/details/symphonyno.9_201912/
Your add on fail to grasp individual file & FAIL ALSO TO GRASP ALL FILE DOWNLOADING OPTION IN SINGLE ARCHIVE FILE !

Other example:
https://archive.org/details/tchaikovskysswanlake
this page contain one track.

Please your kind fix for this.

**Comment by jingyu9575** [comment]
Yes it is the same as #88. It is to prevent conflict with browser preview.

**Comment by Nokia808** [comment]
Thank you very much for your very hard efforts !
But I noticed - & I'm still on version 2.6 of your addon - that addon now CAN GRAB archive (.zip) files from Internet Archive when I check "enable prompt for links without multithreading download" option! I tried same link that I'm already given you ! Is I was confused about archive (.zip) file ?! I remember that it was not grasped ..... !!

Certainly I was confused when I said .zip archive file download links from Internet Archive supporting multithreaded download, because they are really not supporting multithreaded downloaded.

But the audio file links on Internet Archive certainly supporting multithreaded download.

Sorry if any wrong data I gave.

**Comment by jingyu9575** [comment]
Yes the zip file does not support multithreaded download, and the `enable links without multithreading` must be selected to grab such links. They are probably compressed by the server on the fly (only when a user requests a download), and since the zip file is not actually stored in the server, it is not possible for the second thread to start in the middle.

The audio option will be in the next version. There are lots of issues in this repo right now so I'll update it after looking into them.
