### ISSUE TITLE
WARNING: Firefox 74 removed a crucial function

### ISSUE THREAD

**Issue by jingyu9575** [jingyu9575/multithreaded-download-manager#126]
This extension is found to be incompatible with Firefox 74, because a crucial function has been [removed](https://bugzilla.mozilla.org/show_bug.cgi?id=1607791) by Mozilla.

Firefox 74 is currently in the Nightly channel, and will be released on 2020-03-10.

I'm trying to find a workaround as soon as possible. Even if there is a workaround, it will not be possible to continue existing downloads before applying the change. 

If you are downloading a large file currently, it is suggested to postpone updating Firefox until the download completes.

---

请注意：火狐 74 [删除了](https://bugzilla.mozilla.org/show_bug.cgi?id=1607791)扩展使用的重要功能，导致扩展不再兼容。

我正在寻找替代方案。即使有替代方案，也不可能在切换后继续未完成的下载。

如果你正在下载大文件，建议在下载完成之前不要更新浏览器。

**Comment by Nokia808** [comment]
@jingyu9575 
Thank you very much for your very hard work! It was a great shock yesterday when we saw this issue, & it is a happy event that you could fix it currently!

I read in release notes of version 2.10 the following: "This version is able to workaround this issue, but the performance of saving files will decrease."

Can you kindly inform us how the "performance of saving files decreased" ? What was original limits & what is the current limits ? I did not feel that something decreased! It will be more useful if you explain more about this point so that users can avoid losses .....

Best regards.

**Comment by Mike-Reddick** [comment]
> Version 2.10 is able to workaround this issue, but the performance of saving files will decrease

this affect firefox below 74?

**Comment by jingyu9575** [comment]
@Nokia808 You know the file is first downloaded into extension storage, and then saved to the download folder. Without `getFile`, it is no longer possible to do the 2nd step. However, it is currently still possible to read this file. So I workaround it by read each 128MB of the file, and then converted it into standard storage format. Once all the 128MB slices are converted, it will be possible to save them together.
Therefore one more copy is required in the save step. The saving (![screenshot](https://user-images.githubusercontent.com/8923139/72688482-02bded00-3b08-11ea-8562-35e56b9f36dd.png)) time will increase, and you need 128MB memory and more free disk spaces to complete the download. The maximum download speed has not changed yet.

@Mike-Reddick It only affects 74+, when lack of `getFile` is detected..

**Comment by Mike-Reddick** [comment]
I find very annoying and disrespect this mozilla change, I'm rooting for this extension, thanks.

**Comment by jingyu9575** [comment]
Update: This issue has a workaround now, but Firefox is [planning to remove](https://bugzilla.mozilla.org/show_bug.cgi?id=1607791#c13) the entire `IDBMutableFile` in the near future. There are workarounds with caveats.

The status will be tracked on #128.
