### ISSUE TITLE
firefox 75beta not compatible

### ISSUE THREAD

**Issue by Remonli** [jingyu9575/multithreaded-download-manager#137]
Hi , 

Got err msg on 75beta as below : 

```
[
	{
		"level": "error",
		"message": "未知错误: The operation failed for reasons unrelated to the file storage itself and not covered by any other error code.",
		"date": "2020-03-11T05:32:40.634Z",
		"line": "/background/multithreaded-task.js:569:21",
		"extra": {
			"name": "UnknownError",
			"message": "The operation failed for reasons unrelated to the file storage itself and not covered by any other error code.",
			"stack": ""
		},
		"stack": [
			"fail@moz-extension://40d30d4e-e170-466d-8b7f-fe16f813f883/background/multithreaded-task.js:569:21",
			"saveFile@moz-extension://40d30d4e-e170-466d-8b7f-fe16f813f883/background/multithreaded-task.js:478:22"
		]
	}
]
```
Pls help chk ? thanks.

**Comment by jingyu9575** [comment]
Looks like Firefox is finally removing the IDBMutableFile API in 75. Please see #128 for details. 

For now, you can change the storage API to *Segmented files* in the *Advanced* tab in the options. This option only works for new downloads, so if you have a very large existing download, I suggest downgrade to 74 to complete it. Also, with this API you need to manually pause all downloads before existing Firefox, otherwise some progress will be lost.

I'll probably need to make *Segmented files* the default in Firefox 75+.

**Comment by Retia-Adolf** [comment]
This is so sad ;_;

**Comment by jingyu9575** [comment]
Now *Segmented files* is the default option. This should be resolved, but there are [caveats](https://github.com/jingyu9575/multithreaded-download-manager/wiki/Important-changes-for-Firefox-75).
