### ISSUE TITLE
Downloads Appeare In Both the MDM & Firefox's Download Queues

### ISSUE THREAD

**Issue by kenreeser** [jingyu9575/multithreaded-download-manager#147]
Sometime ago, I noticed downloads began to appear in both the Multithreaded Download Manager (MDM) and Firefox's download queues. This behavior didn't always occur. Is this a bug, or normal behavior? I've attached a copy of my MDM prefs.

![2020-05-27_01-43-20](https://user-images.githubusercontent.com/13957237/82982134-7e024480-9fbb-11ea-94f7-730011f46018.png)

**Comment by jingyu9575** [comment]
After the download reaches 100%, the extension will save the file using the built-in download manager. It is the only way for extensions to write files to the disk. 

The built-in download item will not be removed immediately, because it is needed for the "open" and "delete file" functions. If the download task is deleted from the extension, the item will be deleted from the built-in manager as well (unless Firefox has been restarted; this is a bug of Firefox).
