### ISSUE TITLE
Does this is of any relation to your extension development ?

### ISSUE THREAD

**Issue by Nokia808** [jingyu9575/multithreaded-download-manager#155]
@jingyu9575 
Hi. I discovered this issue which is already fixed:
https://bugzilla.mozilla.org/show_bug.cgi?id=1579911

Kindly, see it if it could be of relation to your extension.

Best.

**Comment by jingyu9575** [comment]
I've just tried this new feature. It seems that it opens possibilities to:

* Show the save as dialog at the beginning of the task, instead of after completion
* Warn users about unning tasks on exiting

However, these require a new network connection to a certain type of server, which may raise privacy concerns.

**Comment by Nokia808** [comment]
@jingyu9575 
Hi. Nice to see you in good health !
Do not use it if it has impact on privacy. I thought it of some thing else of benefit like assist in saving of download after exit FF without any loss ..... But if it's use is only what you mentioned, then it is useless & utilizing it will effect your extension negatively so do not use it at all .....
