### ISSUE TITLE
not working anymore

### ISSUE THREAD

**Issue by StellarisStudio** [jingyu9575/multithreaded-download-manager#156]
not working anymore on linux Opensuse Leap 15.2 with firefox 80.0 64bit.. The windows open but stay empty and than the firefox default download windows open and take back control!

**Comment by Nokia808** [comment]
Hi. I test this on my Fedora Linux 32 X64 Cinnamon edition with Firefox version 80.0 X64 bit installed from official Fedora repositories. It is working very okay on my system & I could not reproduce this issue !

It seem that this issue specific to OpenSUSE, may be due to error in their package of Firefox. For that, I recommend you to report this to OpenSUSE ....

Best.

**Comment by jingyu9575** [comment]
I cannot reproduce it on CentOS 7 either. I'll test with openSUSE later.

I remember there is a Firefox-KDE integration package in openSUSE, which used to cause some problem on my system. Have you tried with freshly downloaded Firefox from mozilla.org, not from zypper?

**Comment by jingyu9575** [comment]
I still cannot reproduce it on openSUSE.

![图片](https://user-images.githubusercontent.com/8923139/91822273-174f8f80-ec6a-11ea-803b-b29a7ca7fd48.png)

**Comment by StellarisStudio** [comment]
The multithreaded download stay empty.... and after few seconds the default one arrive..
On firefox 80.0.1 64bit coming from the mozilla depo

> Name 	Firefox
Version 	80.0.1
Build ID 	20200831163820
Distribution ID 	openSUSE
User Agent 	Mozilla/5.0 (X11; Linux x86_64; rv:80.0) Gecko/20100101 Firefox/80.0
OS 	Linux 5.3.18-lp152.36-default #1 SMP Tue Aug 18 17:09:44 UTC 2020 (885251f)
![Screenshot_20200910_192329](https://user-images.githubusercontent.com/20983400/92774167-7cf3f800-f39d-11ea-9d6e-fe575a52f66e.png)
