### ISSUE TITLE
Google Drive

### ISSUE THREAD

**Issue by vlldk** [jingyu9575/multithreaded-download-manager#19]
The extension doesn't give me a progress bar, a % of how much it has downloaded and how large the file is when downloading from Google Drive - [JDownloader](http://jdownloader.org/home/index) (open source) has this feature... And when i click download from the web it defaults to use Firefox' downloader instead...

**Comment by jingyu9575** [comment]
This is because Google Drive's server does not provide the [file size](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Length). Since the size is unknown and multithreading is not possible,  the extension cannot improve the download speed. In this case, it will not automaticly prompt, so that you can choose "open" or "save" in the built-in download more easily. 

Firefox's built-in download and DownThemAll also show the same behavior.

I cannot get JDownloader to work with Google Drive links. When I add the link, it always says "file not found".

![default](https://user-images.githubusercontent.com/8923139/37595484-5346f530-2bbc-11e8-90b1-ce22f45ff036.png)
![default](https://user-images.githubusercontent.com/8923139/37595143-08b458ec-2bbb-11e8-8782-1f35b0f431de.png)

**Comment by jingyu9575** [comment]
Looks like jDownloader uses [a site-specific plugin](https://github.com/mirror/jdownloader/blob/master/src/jd/plugins/hoster/GoogleDrive.java) to get the size. There are over 1000 such [plugins](https://github.com/mirror/jdownloader/tree/master/src/jd/plugins/hoster) in jDownloader.

**Comment by vlldk** [comment]
Great! Maybe implement user useful features too?

**Comment by jingyu9575** [comment]
File size detection for Google Drive is added to v1.5a0, behind the option "Enable specific behaviors for certain websites". This option is not checked by default, because these site-specific code is unstable and may break if Google change the website.

> when i click download from the web it defaults to use Firefox' downloader instead

An option "Enable prompt for links without multithreading support" is also added.

If you find problems in these features, feel free to reopen the issue.

**Comment by memories169** [comment]
Now Google Drive server does provides file size via content-length header, but not provide accept-range. Hope you can make MDM can download Google Drive link with multi-thread
