### ISSUE TITLE
Detecting if links suport multithread

### ISSUE THREAD

**Issue by rayman89** [jingyu9575/multithreaded-download-manager#21]
Would be possible to make the addon able to detect if the server supports multiple connections and resuming and telling it to the user on the accept download window?

**Comment by jingyu9575** [comment]
If multiple connections are not supported, the dialog will not popup by default.

Resuming and multiple connections are the same server feature, since using multiple connections is just resuming from multiple points. 

Are you using the new option "Enable prompt for links without multithreading support"?

**Comment by rayman89** [comment]
I wasn't aware that that feature was innate. I haven't found anything that says it.. I think that would be nice to say it somewhere. The AMO page I think is rather turning people off with the risk warning other than anything.

**Comment by jingyu9575** [comment]
In v1.5a1, if the option "Enable prompt for links without multithreading support" is enabled, and the link does not support multiple connections, the accept download window will show a message.

I will try improving the documentation and the AMO page.
