### ISSUE TITLE
Turbobit downloads

### ISSUE THREAD

**Issue by happysurf** [jingyu9575/multithreaded-download-manager#29]
On Turbobit the downloads appear on MDM compatible with multiple connections but instead it is not supported.
For this reason the task remain blocked.
Example: http://turbobit.net/x3113gqljzck.html

**Comment by jingyu9575** [comment]
The server lies about multiple connection support. It says multiple connections and resuming are supported in the first connection's ["Accept-Ranges" header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Ranges), but when an additional connection is made, the server rejects it.

![default](https://user-images.githubusercontent.com/8923139/41187295-dbb063a0-6bd8-11e8-9bb8-cad1375e3eca.png)

I cannot think of any way to deal with these lying servers. Since lots of "freemium" file cloud sites are doing this, I suggest using "Continue in browser" in these sites.

**Comment by happysurf** [comment]
Thanks for detailed explanation.
