### ISSUE TITLE
[Suggestion] White icon

### ISSUE THREAD

**Issue by happysurf** [jingyu9575/multithreaded-download-manager#4]
Please provide a white icon for dark personas themes.
Thanks.

**Comment by happysurf** [comment]
Thank you for adding in version 0.6 the light icon but I don't see any way for change it in Options > Interface.
Firefox 58 beta11 + Windows 10.

**Comment by jingyu9575** [comment]
The browser should choose the dark/light icon based on the theme.
In case the browser choose the wrong icon, an option is now added (184aa153175b2b02c39b3a2a099a01ad45b16ed2) .

**Comment by happysurf** [comment]
OK now works fine.
Just a clarification, the icon is not white like those Photon Firefox, but is not a big deal.
[white](https://user-images.githubusercontent.com/13637587/33941351-9c600f90-e012-11e7-98e4-3b450be982eb.png)

**Comment by jingyu9575** [comment]
The icon's color is set according to the [official guideline](https://design.firefox.com/photon/visuals/iconography.html#color). It may be incorrect, but the lightness is the other way around in the default dark theme, so a simple tuning does not work.
![default](https://user-images.githubusercontent.com/8923139/33973636-e9c61368-e0be-11e7-891b-074feb4d9b8e.png)
Extensions cannot get the exact color that Firefox uses, and the [upstream bug report](https://bugzilla.mozilla.org/show_bug.cgi?id=1391980) is closed as won't-fix, because they want to develop a more standards-compliant solution.

**Comment by happysurf** [comment]
You are right, for Firefox dark theme the color is Grey 10 #f9f9fa, with an 80% of opacity.
But if you use a dark personas theme like Black Solid > https://addons.mozilla.org/en-US/firefox/addon/black-solid/https://addons.mozilla.org/en-US/firefox/addon/black-solid/ all the icons are inverted in pure white #FFFFFF.
Because of this the developer of Reading List > https://addons.mozilla.org/en-US/firefox/addon/readinglist/ provide a light, dark, white and black icons for all situations.

**Comment by jingyu9575** [comment]
Now the choices are light, lighter, white, dark, darker, black. 
Reading List uses an interesting method of embedding all the color choices in one svg file. Thanks for the link.
