### ISSUE TITLE
Downloads badge number not appear

### ISSUE THREAD

**Issue by happysurf** [jingyu9575/multithreaded-download-manager#43]
This morning on the new Firefox 63beta3, the badge downloads number, not appear like in the screenshot below:
With the previous version 62 all is OK.

![badge](https://user-images.githubusercontent.com/13637587/45077166-c1809500-b0ec-11e8-9d99-ce1129f111ef.png)

**Comment by jingyu9575** [comment]
![default](https://user-images.githubusercontent.com/8923139/45153065-570f4800-b205-11e8-9202-3fed8dc25983.png)
This is what I get on 63b3. The text changes to black because of [this](https://bugzilla.mozilla.org/show_bug.cgi?id=1483867#c7). I'll change it back to white with the new API on 63. The background color is still blue when downloading.
Are you using any custom theme or userChrome.css?

**Comment by happysurf** [comment]
Yes, I use this code for a better view of the extension badge on Bookmarks bar:

.toolbarbutton-badge {
  font-size: 10px !important;
  font-family: Segoe UI !important;
  **color: white !important;**
  margin-top: -7px !important;
  background-color: black !important;
}`

Then I have added the white color code for fix the problem.
In any case I prefer white color on dark theme like mine.

My theme in FirefoxColor is this:
https://color.firefox.com/?theme=XQAAAALsAAAAAAAAAABBqYhm849SCiazH1KEGccwS-xNVAVa_7kk8UbS6ZqzDA0w-GpJ3WjRBnj0JIiPfBa0JNgh6tGAMB4FTWVxI3Xmq0mZjnW7vTP02fMKERRM3NVAdR37ptoO_DjgBzIQ5L8nCFGyqnCPbJFztP_y14Ub9fM3okhF623tXSbK25Ziev87TMghpZWPYQ4gMizAEzDFCZTnXBPeMM4WH_aw2bG8G0Flg-OFmwNoQvwyusA

**Comment by jingyu9575** [comment]
In v1.9.5.1, the badge text color is changed back to white on Firefox 63. 

Note that the badge background color also indicates the state. If the color is forced to be black in userChrome.css, it will be more difficult to notice download completion (green) or error (red).
