### ISSUE TITLE
Remember Download Settings Across Prompting

### ISSUE THREAD

**Issue by Riajyuu** [jingyu9575/multithreaded-download-manager#56]
~~Just keep it as an object as storage.local.set(), fetch it as storage.local.get() when prompting and use a binding to its value.~~

It seems kept from option page but not prompting window. Is there anything reason for this?

**Comment by jingyu9575** [comment]
The reason is that I often use downloads with different characteristics. For my Internet connection, many servers are fast enough to take all the bandwidth, so only 2 or 4 threads are enough, while some servers have slow per-thread limits and requires 10 or more threads. Therefore, I set the default to 4 in the options and manually adjust to more threads for slow servers. 

Probably an option "remember the settings" can help. I'll consider this in the next version.

**Comment by jingyu9575** [comment]
This feature is added in the upcoming verison v2, which is still under testing. The unsigned extension XPI can be found in [Releases](https://github.com/jingyu9575/multithreaded-download-manager/releases).
