### ISSUE TITLE
Check Hash After Downloading

### ISSUE THREAD

**Issue by Riajyuu** [jingyu9575/multithreaded-download-manager#57]
This may be a bit complex than how it looks as I don't find any library in good maintenance status.
Required algorithm can be MD5/SHA128/SHA256.

---

Note if you are to implement #56 , this shall not be kept anyway.

**Comment by jingyu9575** [comment]
I've considered this before. The hash library must have the following features:

1. Incremental. It must accept data with multiple parts and process only one part at a time, or Firefox will be out of memory for large downloads.
2. Works with ArrayBuffer (raw binary data) instead of strings (texts).
3. Fast enough.

It seems that Firefox's built-in [hash functions](https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/digest) are not incremental. The [jsSHA library](https://github.com/Caligatio/jsSHA) seems to be a good candidate.

---

I'm currently working on v2 of this extension privately. As it is a complete rewrite and there are many features planned (e.g. another connection mechanism, batch-download links in page), I'll need some time for new feature enhancements.

**Comment by jingyu9575** [comment]
It turns out that doing hash with JS is really slow. I can only get 14.6 MB/s on my i7 laptop. So I think it is only useful for small files.

**Comment by jingyu9575** [comment]
This feature is added in the upcoming verison v2, which is still under testing. The unsigned extension XPI can be found in [Releases](https://github.com/jingyu9575/multithreaded-download-manager/releases).

---

It currently only supports SHA-1 and SHA-256 though, because asmcrypto.js does not support MD5. As MD5 is not considered secure anymore, how often do you see a download with MD5 hash only? Perhaps I can rewrite the MD5 algorithm in asm.js for reasonable speed, but it will be a difficult work.
