### ISSUE TITLE
Nightly support

### ISSUE THREAD

**Issue by Rigido71** [jingyu9575/multithreaded-download-manager#60]
Hi,
I was wondering if it is ok to report issues with Nightly builds 69.0a1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0 ID:20190604034844).

If so, please note that current version doesn't work on latest Nighlty, nothing happens clicking on a link (with Automatically option flagged) nor using the context menu. 

I hope on a future less minimalist UI...

Thanks.

**Comment by jingyu9575** [comment]
I just tested on Nightly 20190604034844 and have not seen any problems. Please check the console log (`about:debugging#addons`, click "Inspect" on this extension, "Console" tab) to see whether there are error messages. 

> a future less minimalist UI

What features do you suggest?

**Comment by Rigido71** [comment]
Hi,
after a reboot MDM seems to work and properly prompt for download, sorry for that.

> What features do you suggest? 

I just started using MDM and actually there are any new features I would like to see. There are some behaviors that I know are not your fault but Firefox restrictions on plugins.
Right now I would start using the same UI font as the whole browser :)
I find Times New Roman a little bit ugly on a UI.

BTW, I tried to debug the plugin and found this warning:
> The ‘storage’ attribute in options passed to indexedDB.open is deprecated and will soon be removed. To get persistent storage, please use navigator.storage.persist() instead.

and I tried to download from an IBM ftp site (ftp://index.storsys.ibm.com/tivoli-storage-management/patches/server/AIX/8.1.6.200/8.1.6.200-IBM-SPSRV-AIX.bin) but when I saw that that would not be a multi-threaded download:
![2019-06-05_10h51_01](https://user-images.githubusercontent.com/29772377/58943516-31a56f80-8780-11e9-8c0e-1a21973a7456.png)
I pressed Cancel and the error appeared:
![2019-06-05_10h51_28](https://user-images.githubusercontent.com/29772377/58943543-3cf89b00-8780-11e9-9e47-934738fc7b21.png)

Thank you!

**Comment by jingyu9575** [comment]
> using the same UI font as the whole browser

Actually I was trying to use the same font, and it is correct on my system.
It is probably because of a syntax error that will be fixed in v2. I've made a patch on v1. Please update the extension and see if the problem still exists. 

> debug the plugin and found this warning

This is fine. The first version v0 of this extension is using an old method to access Firefox's persistent storage. Now this method is deprecated by Firefox, and v1 starts to use the new method. However the old storage must still be checked for backward compatibility, otherwise updating to v1 while downloading will cause the data to be inaccessible.

The next version v2 will remove the old code and the warning will be gone.

> ftp site
FTP is not supported, because as far as I know multi-threading FTP is not possible in Firefox extensions.
Showing this dialog should be a bug, since it is not possible to use this extension to download FTP files. I'll see if it is easy to fix in v1.

**Comment by jingyu9575** [comment]
This issue is fixed in the upcoming verison v2, which is still under testing. The unsigned extension XPI can be found in [Releases](https://github.com/jingyu9575/multithreaded-download-manager/releases).
