### ISSUE TITLE
No automatic grab of PDF !

### ISSUE THREAD

**Issue by Nokia808** [jingyu9575/multithreaded-download-manager#88]
Hi. Your extension do not currently automatically grab PDF files. PDF have to be opened 1st then manually click on download link ! Look for this example:
https://ia800904.us.archive.org/7/items/WorldTheater00003/World-Theater-00003.pdf

**Comment by Nokia808** [comment]
I'm not sure whether same issue or should be in separate thread: the following link when click on download it will pass directly to browser build-in downloader - NOT opened 1st as for link in my 1st comment above in this thread. 

If not related, so you can delete this comment & ask me to open new issue about it.

https://www.hindawi.org/books/93028137/

**Comment by jingyu9575** [comment]
> not currently automatically grab PDF files

Grabing them will interfere with the built-in PDF preview feature. Do you use this feature?

![图片](https://user-images.githubusercontent.com/8923139/64676172-95d67e80-d4a7-11e9-8a84-5330f88eb624.png)

> the following link when click on download it will pass directly to browser build-in downloader

This link does not support multithreading at all. By default, the extension does not grab such links, because it cannot improve the download speed. If the option "Enable prompt for links without multithreading support" is enabled, the extension will be able to see this link.

**Comment by Nokia808** [comment]
@jingyu9575 
Dear regarding automatic grab of PDF, I know that it interfere with view of PDF. In fact certain users prefer not to view PDF before downloading it, while other user prefer to view PDF before downloading PDF. 
Personally, if PDF is of large size, it then will be very great to disable view it before download & it will be much better to download it 1st then view it as the downloader increase download speed .....
For that I suggest on you to add new option: "automatically grab PDF" & make it disabled by default & user can enable/disable it as she/he need. This will be nice. If you accept this suggestion then please re-open this issue.

**Comment by Nokia808** [comment]
@jingyu9575 
Many thanks ! Really working very well !
